/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tournament;

/**
 *
 * @author Kyle
 */
public class BracketSize extends javax.swing.JFrame {

    /**
     * Creates new form BracketSize
     */
    public BracketSize() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        twoPlay = new javax.swing.JButton();
        fourPlay = new javax.swing.JButton();
        fivePlay = new javax.swing.JButton();
        sixPlay = new javax.swing.JButton();
        sevenPlay = new javax.swing.JButton();
        eightPlay = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        twoPlay.setText("2 Players");
        twoPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoPlayMouseClicked(evt);
            }
        });

        fourPlay.setText("4 Players");
        fourPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourPlayMouseClicked(evt);
            }
        });

        fivePlay.setText("5 Players");
        fivePlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fivePlayMouseClicked(evt);
            }
        });

        sixPlay.setText("6 Players");
        sixPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixPlayMouseClicked(evt);
            }
        });

        sevenPlay.setText("7 Players");
        sevenPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenPlayMouseClicked(evt);
            }
        });

        eightPlay.setText("8 Players");
        eightPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightPlayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sixPlay)
                        .addGap(18, 18, 18)
                        .addComponent(sevenPlay)
                        .addGap(18, 18, 18)
                        .addComponent(eightPlay))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(twoPlay)
                        .addGap(18, 18, 18)
                        .addComponent(fourPlay)
                        .addGap(18, 18, 18)
                        .addComponent(fivePlay)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twoPlay)
                    .addComponent(fourPlay)
                    .addComponent(fivePlay))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixPlay)
                    .addComponent(sevenPlay)
                    .addComponent(eightPlay))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void twoPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoPlayMouseClicked
        AddPlayers itemLoader = new AddPlayers(2);
        itemLoader.setSize(500, 500);
        itemLoader.setVisible(true);
        this.setVisible(true);
        itemLoader.toFront();
        this.dispose();
    }//GEN-LAST:event_twoPlayMouseClicked

    private void fourPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourPlayMouseClicked
        AddPlayers itemLoader = new AddPlayers(4);
        itemLoader.setVisible(true);
        this.setVisible(true);
        itemLoader.toFront();
        this.dispose();
    }//GEN-LAST:event_fourPlayMouseClicked

    private void fivePlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fivePlayMouseClicked
        AddPlayers itemLoader = new AddPlayers(5);
        itemLoader.setVisible(true);
        this.setVisible(true);
        itemLoader.toFront();
        this.dispose();
    }//GEN-LAST:event_fivePlayMouseClicked

    private void sixPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixPlayMouseClicked
        AddPlayers itemLoader = new AddPlayers(6);
        itemLoader.setVisible(true);
        this.setVisible(true);
        itemLoader.toFront();
        this.dispose();
    }//GEN-LAST:event_sixPlayMouseClicked

    private void sevenPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenPlayMouseClicked
        AddPlayers itemLoader = new AddPlayers(7);
        itemLoader.setVisible(true);
        this.setVisible(true);
        itemLoader.toFront();
        this.dispose();
    }//GEN-LAST:event_sevenPlayMouseClicked

    private void eightPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightPlayMouseClicked
        AddPlayers itemLoader = new AddPlayers(8);
        itemLoader.setSize(500, 500);
        itemLoader.setVisible(true);
        this.setVisible(true);
        itemLoader.toFront();
        this.dispose();
    }//GEN-LAST:event_eightPlayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BracketSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BracketSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BracketSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BracketSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BracketSize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eightPlay;
    private javax.swing.JButton fivePlay;
    private javax.swing.JButton fourPlay;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton sevenPlay;
    private javax.swing.JButton sixPlay;
    private javax.swing.JButton twoPlay;
    // End of variables declaration//GEN-END:variables
}
